#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".
set -e

echo "[pre-commit] update single header file..."
cd scripts
python combine_src_to_header_only.py
cd ..

echo "[pre-commit] update single test file..."
cd scripts
python combine_tests_to_single.py
cd ..

git add single/